# Generated by Django 6.0.1 on 2026-01-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=50)),
                ('fare_per_km', models.IntegerField()),
                ('image', models.ImageField(upload_to='cars/')),
            ],
        ),
    ]
