# Generated by Django 6.0.1 on 2026-01-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fare_per_km',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
