# Generated by Django 6.0.1 on 2026-01-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_is_available_car_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Seats',
            field=models.IntegerField(default=4),
        ),
    ]
