# Generated by Django 6.0.1 on 2026-01-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Seats',
            new_name='seats',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Luxury', 'Luxury'), ('Electric', 'Electric')], max_length=50),
        ),
    ]
