# Generated by Django 6.0.1 on 2026-01-28 15:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0006_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_lng', models.FloatField(blank=True, null=True)),
                ('end_lat', models.FloatField(blank=True, null=True)),
                ('end_lng', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('total_days', models.PositiveIntegerField(default=1)),
                ('total_km', models.FloatField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
